Repository flood-io/element, pull requests merged in 2020-04, with the labels that each got.

#114 Revert flood file path
  packages/core/src/types.ts
  packages/flood-runner/src/ConcurrencyHack.ts
  packages/flood-runner/src/Environment.ts
  packages/flood-runner/src/Logger.ts
  packages/flood-runner/src/MetricIdentifier.ts
  packages/flood-runner/src/tickerInterval.ts
Labels: bug

#125 Beta 1.2.3
  .vscode/launch.json
  CHANGELOG.md
  lerna.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/compiler/CHANGELOG.md
  packages/compiler/package.json
  packages/core/CHANGELOG.md
  packages/core/api.ts
  packages/core/index.ts
  packages/core/package.json
  packages/core/src/network/Protocol.ts
  packages/core/src/page/Condition.ts
  packages/core/src/page/Locator.ts
  packages/core/src/page/Until.ts
  packages/core/src/page/conditions/DialogCondition.spec.ts
  packages/core/src/page/conditions/DialogCondition.ts
  packages/core/src/page/conditions/ElementSelectedCondition.ts
  packages/core/src/page/conditions/ElementStateCondition.ts
  packages/core/src/page/conditions/ElementTextCondition.ts
  packages/core/src/page/conditions/ElementVisibilityCondition.ts
  packages/core/src/page/locators/VisibleTextLocator.spec.ts
  packages/core/src/runtime-environment/NullRuntimeEnvironment.ts
  packages/core/src/runtime-environment/WorkRoot.ts
  packages/core/src/runtime-environment/types.ts
  packages/core/src/runtime/Browser.ts
  packages/core/src/runtime/EvaluatedScript.ts
  packages/core/src/runtime/EvaluatedScriptLike.ts
  packages/core/src/runtime/ITest.ts
  packages/core/src/runtime/Test.ts
  packages/core/src/runtime/test-observers/Inner.ts
  packages/core/src/runtime/test-observers/Observer.ts
  packages/core/src/test-data/TestDataLoaders.ts
  packages/core/src/utils/ObjectTrace.spec.ts
  packages/core/src/utils/ObjectTrace.ts
  packages/core/tests/support/test-reporter.ts
  packages/element-api/CHANGELOG.md
  packages/element-api/package.json
  packages/element-cli/CHANGELOG.md
  packages/element-cli/package.json
  packages/element/CHANGELOG.md
  packages/element/package.json
  packages/flood-runner/CHANGELOG.md
  packages/flood-runner/package.json
  packages/flood-runner/src/Environment.ts
  packages/flood-runner/src/Grid.ts
  packages/flood-runner/src/InfluxReporter.ts
  packages/flood-runner/src/MetricIdentifier.ts
Labels: docs, enhancement

#131 feat: text not match waiters
  packages/core/src/page/Until.ts
  packages/core/src/page/conditions/ElementTextNotMatchCondition.spec.ts
  packages/core/src/page/conditions/ElementTextNotMatchCondition.ts
Labels: enhancement, feature request
